In [1]:
import pandas as pd
import numpy as np

In [23]:
order_items = pd.read_csv(r"C:\Users\harsh\OneDrive\Desktop\FINAL_DA_DATASET\olist_order_items_dataset.csv")

In [24]:
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [25]:
order_items['shipping_limit_date']=pd.to_datetime(order_items['shipping_limit_date'])

In [34]:
order_items

,order_id,order_item_id,product_id,seller_id,price,freight_value,shipping_date,shipping_time
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29,2017-09-19,09:45:35
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93,2017-05-03,11:05:13
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87,2018-01-18,14:48:30
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79,2018-08-15,10:10:18
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14,2017-02-13,13:57:51
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,299.99,43.41,2018-05-02,04:11:01
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,350.00,36.53,2018-07-20,04:31:48
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,99.90,16.95,2017-10-30,17:14:25
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,55.99,8.72,2017-08-21,00:04:32
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,43.00,12.79,2018-06-12,17:10:13

In [31]:
order_items['shipping_date'] = order_items['shipping_limit_date'].dt.date
order_items['shipping_time'] = order_items['shipping_limit_date'].dt.time

In [33]:
order_items.drop(['shipping_limit_date'], inplace = True, axis = 1)

# product

In [35]:
product = pd.read_csv(r"C:\Users\harsh\OneDrive\Desktop\FINAL_DA_DATASET\olist_products_dataset.csv")

In [39]:
pd.set_option('display.max_rows', 50)
product.head(50)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,60.0,745.0,1.0,200.0,38.0,5.0,11.0
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,56.0,184.0,2.0,900.0,40.0,8.0,40.0
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,57.0,163.0,1.0,400.0,27.0,13.0,17.0
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,36.0,1156.0,1.0,600.0,17.0,10.0,12.0
10,14aa47b7fe5c25522b47b4b29c98dcb9,cama_mesa_banho,54.0,630.0,1.0,1100.0,16.0,10.0,16.0
11,03b63c5fc16691530586ae020c345514,bebes,49.0,728.0,4.0,7150.0,50.0,19.0,45.0
12,cf55509ea8edaaac1d28fdb16e48fc22,instrumentos_musicais,43.0,1827.0,3.0,250.0,17.0,7.0,17.0
13,7bb6f29c2be57716194f96496660c7c2,moveis_decoracao,51.0,2083.0,2.0,600.0,68.0,11.0,13.0
14,eb31436580a610f202c859463d8c7415,construcao_ferramentas_seguranca,59.0,1602.0,4.0,200.0,17.0,7.0,17.0
15,3bb7f144022e6732727d8d838a7b13b3,esporte_lazer,22.0,3021.0,1.0,800.0,16.0,2.0,11.0
16,6a2fb4dd53d2cdb88e0432f1284a004c,perfumaria,39.0,346.0,2.0,400.0,27.0,5.0,20.0
17,a1b71017a84f92fd8da4aeefba108a24,informatica_acessorios,59.0,636.0,1.0,900.0,40.0,15.0,20.0
18,a0736b92e52f6cead290e30b578413b6,moveis_decoracao,56.0,296.0,2.0,1700.0,100.0,7.0,15.0
19,f53103a77d9cf245e579ea37e5ec51f0,cama_mesa_banho,52.0,206.0,1.0,500.0,16.0,10.0,16.0
20,1c1890ba1779090cd54008a3c3302921,moveis_decoracao,27.0,158.0,4.0,2550.0,29.0,24.0,45.0
21,518ef5de2c2b3a255e326a4594ba15d9,cama_mesa_banho,27.0,329.0,2.0,800.0,36.0,8.0,16.0
22,e3e020af31d4d89d2602272b315c3f6e,beleza_saude,58.0,1987.0,3.0,75.0,21.0,7.0,13.0
23,8b41fbc2b984a12030090112324d1bc4,bebes,55.0,1627.0,1.0,500.0,20.0,13.0,13.0
24,d03bd02af9fff4b98f1c972315e5e9ef,moveis_decoracao,56.0,209.0,1.0,1800.0,40.0,10.0,30.0
25,8ba4f2a4ae695d26e5626c1bf710975e,utilidades_domesticas,52.0,968.0,1.0,900.0,50.0,5.0,50.0
26,f6574524b07d5bb753bab6f35abe2d06,malas_acessorios,52.0,573.0,5.0,3600.0,35.0,25.0,50.0
27,c78b767da00efb70c1bcccab87c28cd5,informatica_acessorios,35.0,1101.0,2.0,300.0,42.0,2.0,30.0
28,a0253d43394dd4da9a5d7b1f546f1a32,informatica_acessorios,59.0,1890.0,2.0,740.0,23.0,13.0,13.0
29,051b9ff13dd55c0a6655a15ff296f80d,esporte_lazer,50.0,529.0,2.0,3600.0,62.0,23.0,23.0
30,47859fca9dd7485cbd93c3e8993bb74f,cama_mesa_banho,45.0,206.0,1.0,650.0,16.0,10.0,16.0
31,e1d1d22e9f8122a4ec1533b032c12562,ferramentas_jardim,49.0,1163.0,9.0,2150.0,70.0,8.0,34.0
32,20e37962088a4061d3578def47a8648b,moveis_decoracao,60.0,208.0,1.0,800.0,40.0,10.0,34.0
33,1eba879220bd0981a0e2fbab499ed4e1,moveis_escritorio,57.0,476.0,1.0,8950.0,52.0,51.0,17.0
34,ce5b91848b91118daffb3af53b747475,esporte_lazer,50.0,699.0,4.0,1388.0,34.0,9.0,31.0
35,5370b82a213393979691c98074265584,bebes,52.0,708.0,9.0,7950.0,33.0,30.0,44.0
36,b8dac5113b06a97e64943234522572b9,automotivo,43.0,1062.0,2.0,6000.0,87.0,3.0,42.0
37,750cf819d127191920eda79a4b6fb479,eletronicos,31.0,806.0,1.0,263.0,18.0,12.0,16.0
38,e6af694343b45b56304ad91974a110b9,utilidades_domesticas,37.0,352.0,1.0,3900.0,19.0,20.0,15.0
39,680874c570dad71c0a2844cfbf417054,moveis_decoracao,47.0,502.0,1.0,600.0,25.0,25.0,25.0
40,8b3a9476f74f5297f7ff0ec6d95fe1ea,moveis_decoracao,63.0,254.0,2.0,2050.0,49.0,13.0,41.0
41,1c6fb703c624b381a20f21f757694866,brinquedos,33.0,471.0,2.0,725.0,22.0,17.0,15.0
42,db46052aed7dff59ba38cf2fe29b87f9,cama_mesa_banho,56.0,509.0,4.0,6350.0,45.0,15.0,35.0
43,b864b103180d5a6a3f830e67f93e8735,bebes,47.0,980.0,4.0,600.0,70.0,11.0,11.0
44,7a8dac4aaa16bc642e4df33adcf03303,cool_stuff,38.0,1701.0,2.0,11750.0,18.0,40.0,79.0
45,83b9bc6aae6f527ff6aafb9e01d6cbf3,brinquedos,20.0,866.0,3.0,2550.0,22.0,32.0,38.0
46,5f504b3a1c75b73d6151be81eb05bdc9,cool_stuff,38.0,1176.0,3.0,15350.0,47.0,40.0,47.0
47,bbf920aa6ac72007a726e6f419156f8f,moveis_decoracao,42.0,303.0,2.0,1300.0,25.0,16.0,25.0
48,c3b7e4d83e530c27a8e6368296aece48,moveis_decoracao,60.0,1972.0,2.0,850.0,69.0,11.0,11.0
49,c5d8079278e912d7e3b6beb48ecb56e8,beleza_saude,60.0,330.0,1.0,1300.0,19.0,28.0,17.0

# productname

In [40]:
name = pd.read_csv(r"C:\Users\harsh\OneDrive\Desktop\FINAL_DA_DATASET\product_category_name_translation.csv")

In [41]:
name

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [43]:
order_items.to_csv('order_items_clean.csv', index = False),
product.to_csv('product_clean.csv', index = False),
name.to_csv('name_clean.csv', index = False)

In [44]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Ronaldo%4007@localhost:3306/olist_db"
)

In [45]:
order_items.to_sql(
    'order_items',
    con=engine,
    if_exists='replace',
    index=False
)

112650

In [46]:
product.to_sql(
    'product',
    con=engine,
    if_exists='replace',
    index=False
)

32951

In [47]:
name.to_sql(
    'name',
    con=engine,
    if_exists='replace',
    index=False
)

71

In [48]:
order_items.duplicated().sum()

np.int64(0)

In [49]:
name.duplicated().sum()

np.int64(0)

In [50]:
product.duplicated().sum()

np.int64(0)

In [52]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       112650 non-null  object
 1   order_item_id  112650 non-null  int64
 2   product_id     112650 non-null  object
 3   seller_id      112650 non-null  object
 4   price          112650 non-null  float64
 5   freight_value  112650 non-null  float64
 6   shipping_date  112650 non-null  object
 7   shipping_time  112650 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 6.9+ MB

In [53]:
name.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [54]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [55]:
# there are null values in product

In [57]:
product.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [58]:
product.duplicated(['product_id']).sum()

np.int64(0)

In [60]:
order_items

,order_id,order_item_id,product_id,seller_id,price,freight_value,shipping_date,shipping_time
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29,2017-09-19,09:45:35
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93,2017-05-03,11:05:13
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87,2018-01-18,14:48:30
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79,2018-08-15,10:10:18
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14,2017-02-13,13:57:51
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,299.99,43.41,2018-05-02,04:11:01
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,350.00,36.53,2018-07-20,04:31:48
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,99.90,16.95,2017-10-30,17:14:25
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,55.99,8.72,2017-08-21,00:04:32
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,43.00,12.79,2018-06-12,17:10:13

In [72]:
order_items['Total_Sales'] = order_items['price'] + order_items['freight_value']

In [74]:
order_items

,order_id,order_item_id,product_id,seller_id,price,freight_value,shipping_date,shipping_time,Total_Sales
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29,2017-09-19,09:45:35,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93,2017-05-03,11:05:13,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87,2018-01-18,14:48:30,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79,2018-08-15,10:10:18,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14,2017-02-13,13:57:51,218.04
...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,299.99,43.41,2018-05-02,04:11:01,343.40
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,350.00,36.53,2018-07-20,04:31:48,386.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,99.90,16.95,2017-10-30,17:14:25,116.85
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,55.99,8.72,2017-08-21,00:04:32,64.71
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,43.00,12.79,2018-06-12,17:10:13,55.79

In [75]:
sum(order_items['Total_Sales'])

15843553.24